files:
  - source: /web/app/assets/locales/locale-en.json
    translation: /web/app/assets/locales/locale-%two_letters_code%.json
  - source: /help/en/*.md
    translation: /help/%two_letters_code%/%original_file_name%
  - source: /help/en/accounts/*.md
    translation: /help/%two_letters_code%/accounts/%original_file_name%
  - source: /help/en/assets/*.md
    translation: /help/%two_letters_code%/assets/%original_file_name%
  - source: /help/en/components/*.md
    translation: /help/%two_letters_code%/components/%original_file_name%
  - source: /help/en/dex/*.md
    translation: /help/%two_letters_code%/dex/%original_file_name%
  - source: /help/en/introduction/*.md
    translation: /help/%two_letters_code%/introduction/%original_file_name%
